#pragma once
// Generated by tools/embed-pe-hud.ps1; edit the Lua sources instead.
namespace pe_hud_bridge {
inline constexpr char embeddedLoader[]=R"VALKYRIE_LUA(-- Loaded by the verified native call-site bridge, never appended to hud.lua.
local original,err=loadfile('hud.lua')
if not original then error(err) end
local function pack(...)return {n=select('#',...),...}end
local results=pack(original())
local ok,message=pcall(function()
-- Load AFTER the user's existing hud.lua. Never replace that file or its radar.
-- No rendering, engine flags, radar callbacks, or HUD-wide dispatch hooks here.
local enabled, master, legacy, section = false, nil, true, ""
local hidden = {}
local file = io and io.open and (io.open("valkyrie-atmosphere.ini", "r") or io.open("valkyrie-inventory.ini", "r"))
if file then
    enabled = true
    for line in file:lines() do
        local header = line:match("^%s*%[([^%]]+)%]")
        if header then section = header:lower() end
        local key, value = line:match("^%s*([%w_]+)%s*=%s*(%-?%d+)")
        if key then
            key, value = key:lower(), tonumber(value) ~= 0
            if section == "inventory" and key == "enabled" then enabled = value end
            if section == "hud" then
                if key == "hideplayerhud" then master = value
                elseif key == "hideall" then legacy = value
                else hidden[key] = value end
            end
        end
    end
    file:close()
end
if master == nil then master = legacy end
local parts = {
    RenderClock="hideclock", RenderMoney="hidemoney",
    RenderHealthBar="hidehealth", RenderArmorBar="hidearmour",
    RenderBreathBar="hidebreath", RenderWeaponIcon="hideweaponicon",
    RenderWeaponAmmo="hideammo", RenderWantedLevel="hidewanted"
}
-- Safe on script reload: never wrap our own wrapper recursively.
ValkyrieHudAdapter = ValkyrieHudAdapter or { originals={}, wrappers={} }
local adapter = ValkyrieHudAdapter
-- Bloodlines combines four indicators in RenderHealthBar. Keep that callback
-- running (including its smoothing) and filter only its named status rows.
local bloodlines = type(DrawBloodlinesStatusRow) == 'function' and
    type(BL_SmoothHealth) == 'number' and type(BL_SmoothArmor) == 'number' and
    type(BL_SmoothBreath) == 'number' and BL_HEALTH_L and BL_ARMOR_L and BL_HUNGER_L
if bloodlines then
    local original = DrawBloodlinesStatusRow
    if original == adapter.rowWrapper then original = adapter.rowOriginal end
    adapter.rowOriginal = original
    if enabled and master then
        local rowKeys = {[0]='hidehealth',[1]='hidearmour',[2]='hidehunger',[3]='hidebreath'}
        local rowLabels = {[0]='V',[1]='C',[2]='F',[3]='S'}
        adapter.rowWrapper = function(row,label,...)
            local key = rowKeys[row]
            if key and rowLabels[row] == label and hidden[key] ~= false then return end
            return original(row,label,...)
        end
        DrawBloodlinesStatusRow = adapter.rowWrapper
    else
        DrawBloodlinesStatusRow = original
        adapter.rowWrapper = nil
    end
end
if Hud then
    for name, key in pairs(parts) do
        local original = Hud[name]
        if adapter.wrappers[name] and original == adapter.wrappers[name] then original = adapter.originals[name] end
        adapter.originals[name] = original
        if type(original) == "function" then
            if enabled and master and hidden[key] ~= false and not (bloodlines and name == 'RenderHealthBar') then
                local wrapper = function(...) return end
                adapter.wrappers[name] = wrapper
                Hud[name] = wrapper
            else
                Hud[name] = original
                adapter.wrappers[name] = nil
            end
        end
    end
end

end)
if not ok then print('Valkyrie HUD adapter: '..tostring(message))end

local radarOk,radarError=pcall(function()
    local ffi=require('ffi')
    ffi.cdef[[
        void* __stdcall GetModuleHandleA(const char*);
        void* __stdcall GetProcAddress(void*, const char*);
    ]]
    local kernel=ffi.load('kernel32')
    local backend={}
    local bounds=ffi.new('float[4]')
    local layout,draw
    local function resolve()
        if layout and draw then return true end
        local module=kernel.GetModuleHandleA('valkyrie-radar.asi')
        if module==nil then return false end
        local l=kernel.GetProcAddress(module,'ValkyrieRadarLuaLayout')
        local d=kernel.GetProcAddress(module,'ValkyrieRadarLuaDraw')
        if l==nil or d==nil then return false end
        layout=ffi.cast('int (__cdecl*)(float*)',l)
        draw=ffi.cast('int (__cdecl*)(void)',d)
        return true
    end
    function backend.layout()
        if not resolve() or layout(bounds)==0 then return end
        return tonumber(bounds[0]),tonumber(bounds[1]),tonumber(bounds[2]),tonumber(bounds[3])
    end
    function backend.draw()return resolve() and draw()~=0 end
    local install=(function()
-- Preserve the HUD's complete radar callback, including its visibility rules,
-- blips and aircraft instruments. Replace only a successful 3D background pass.
return function(backend)
    if not Hud or type(Hud.RenderRadar)~='function' or type(Hud.DrawRadar)~='function' then return end
    -- Only enable the known coordinate contract; unfamiliar HUDs pass through.
    if not mapOffset or not mapSize or type(TransformRadarPointToScreenSpace)~='function' then return end
    ValkyrieRadarHudAdapter=ValkyrieRadarHudAdapter or {}
    local state=ValkyrieRadarHudAdapter
    if Hud.RenderRadar==state.wrapper then Hud.RenderRadar=state.original end
    local original=Hud.RenderRadar
    state.original=original
    local function pack(...)return {n=select('#',...),...}end
    state.wrapper=function(...)
        local x,y,w,h=backend.layout()
        if not x then return original(...)end
        local offset,size=mapOffset,mapSize
        local ox,oy,sw,sh=offset.x,offset.y,size.x,size.y
        local draw=Hud.DrawRadar
        Hud.DrawRadar=function(...)
            if backend.draw()then
                offset.x,offset.y,size.x,size.y=x,y,w,h
                return
            end
            -- Failed/inactive capture: restore the user's geometry and use
            -- their complete original draw path, never leave a blank panel.
            offset.x,offset.y,size.x,size.y=ox,oy,sw,sh
            return draw(...)
        end
        local results=pack(pcall(original,...))
        Hud.DrawRadar=draw
        offset.x,offset.y,size.x,size.y=ox,oy,sw,sh
        if not results[1]then error(results[2],0)end
        return unpack(results,2,results.n)
    end
    Hud.RenderRadar=state.wrapper
end

end)()
    install(backend)
end)
if not radarOk then print('Valkyrie radar adapter: '..tostring(radarError))end
return unpack(results,1,results.n)
)VALKYRIE_LUA";
}
