# Build the Valkyrie Phone ASI.
#
# An ASI is a DLL the game's loader picks up by extension, so this is an
# ordinary 32 bit DLL build - 32 bit because San Andreas is.
#
#   build.ps1              a development build (with its log) into build/
#   build.ps1 -Install     build, then copy into the game folder
#   build.ps1 -Install -GamePath C:\Games\GTA San Andreas
#   build.ps1 -Clean       throw the build away first
#   build.ps1 -Release     an optimised build with the routine log lines left out
#   build.ps1 -Gta4Path "D:\Games\GTA IV"   where GTA IV is, for the browser's pages
#
# It needs Visual Studio's C++ build tools (x86), and the two submodules:
#   git submodule update --init
param(
    [switch] $Install,
    [string] $OnlyTarget,
    [switch] $Clean,
    [switch] $Release,
    [string] $GamePath,
    # GTA IV, for the phone's browser: its internet is built from the
    # player's own copy (valkyrie-phone\tools\iv-web). Found through Steam
    # or Rockstar's own registry key when not given.
    [string] $Gta4Path
)

$ErrorActionPreference = "Stop"

$root    = Split-Path -Parent $MyInvocation.MyCommand.Path
$build   = Join-Path $root "build"
$game    = $GamePath
# Steam's own folder from the registry, and every library it lists.
function Get-SteamLibraries {
    $steamRoots = @()
    foreach ($key in "HKCU:\Software\Valve\Steam", "HKLM:\SOFTWARE\WOW6432Node\Valve\Steam", "HKLM:\SOFTWARE\Valve\Steam") {
        $item = Get-ItemProperty -Path $key -ErrorAction SilentlyContinue
        foreach ($value in @($item.SteamPath, $item.InstallPath)) { if ($value) { $steamRoots += ($value -replace '/', '\') } }
    }
    $steamRoots += "C:\Program Files (x86)\Steam"
    $libraries = @()
    foreach ($steamRoot in ($steamRoots | Select-Object -Unique)) {
        $libraries += $steamRoot
        $vdf = Join-Path $steamRoot "steamapps\libraryfolders.vdf"
        if (Test-Path -LiteralPath $vdf) {
            foreach ($m in [regex]::Matches((Get-Content -LiteralPath $vdf -Raw), '"path"\s+"([^"]+)"')) {
                $libraries += ($m.Groups[1].Value -replace '\\\\', '\')
            }
        }
    }
    $libraries | Select-Object -Unique
}
# No folder given, or the default one is not there: San Andreas where Steam
# keeps it.
if ([string]::IsNullOrWhiteSpace($game) -or -not (Test-Path -LiteralPath $game)) {
    foreach ($library in (Get-SteamLibraries)) {
        $candidate = Join-Path $library "steamapps\common\Grand Theft Auto San Andreas"
        if (Test-Path -LiteralPath $candidate) {
            $game = $candidate
            Write-Host "[build] game folder: $game (found through Steam)" -ForegroundColor Green
            break
        }
    }
}
if ($Install -and [string]::IsNullOrWhiteSpace($game)) {
    throw "-Install needs the game folder: -GamePath 'C:\path\to\GTA San Andreas' (the folder with gta_sa.exe)"
}
# The phone's version.
$version = "0.2.1"
$phoneVersion = "0.2.5-test"

# Visual Studio 2019 Build Tools. Found rather than hardcoded, because the
# toolset version in the path changes with every update.
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) {
    throw "Visual Studio Build Tools are not installed - no vswhere at $vswhere"
}

$vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $vsPath) {
    # The C++ workload is what actually matters; fall back to any install and
    # let vcvarsall complain if the compiler really is missing.
    $vsPath = & $vswhere -latest -products * -property installationPath
}
if (-not $vsPath) {
    throw "No Visual Studio installation with a C++ compiler"
}

$vcvars = Join-Path $vsPath "VC\Auxiliary\Build\vcvarsall.bat"
if (-not (Test-Path $vcvars)) {
    throw "No vcvarsall.bat at $vcvars"
}

if ($Clean -and (Test-Path $build)) {
    Remove-Item -Recurse -Force $build
}
if (-not (Test-Path $build)) {
    New-Item -ItemType Directory -Path $build | Out-Null
}

# The version goes through a generated header rather than a /D on the command
# line. A quoted string define has to survive PowerShell, then cmd, then the
# compiler's own parsing, and it does not reliably survive all three.
$versionHeader = Join-Path $root "valkyrie-core\src\version.h"
@"
// Generated by build.ps1. Do not edit - your change will be overwritten on the
// next build. The versions live at the top of build.ps1.
#pragma once

#define SPRP_SUITE_VERSION "$version"
#define VALKYRIE_ATMOSPHERE_VERSION "$atmosphereVersion"
#define SPRP_BLIPS_VERSION SPRP_SUITE_VERSION
#define VALKYRIE_MAP_VERSION "$mapVersion"
#define VALKYRIE_RADAR_VERSION "$radarVersion"
#define DOCTOR_VALKYRIE_VERSION "$doctorVersion"
#define VALKYRIE_PHONE_VERSION "$phoneVersion"
"@ | Set-Content -Path $versionHeader -Encoding ASCII
$releaseFlags = @("/GL", "/Gy", "/DNDEBUG", "/Z7")
$flags = (@(
    "/nologo", "/std:c++17", "/EHsc", "/O2", "/MT", "/W4", "/WX", "/utf-8",
    "/DWIN32_LEAN_AND_MEAN", "/DNOMINMAX", "/D_CRT_SECURE_NO_WARNINGS"
) + $(if ($Release) { $releaseFlags }) + @("/LD")) -join " "
$linkFlags = if ($Release) { "/LTCG /OPT:REF /OPT:ICF /DEBUG:FULL" } else { "" }

Write-Host "[build] $(if ($Release) { 'RELEASE (optimized, private symbols, routine logs disabled)' } else { 'development (with diagnostics)' })" -ForegroundColor $(if ($Release) { "Yellow" } else { "Cyan" })

$targets = @(
    @{
        # The SP-RP phone for single player, drawn as the 2007 handset. Its
        # own artwork travels as valkyrie-phone.txd, packed below.
        Name = "valkyrie-phone"
        Module = "valkyrie-phone"
        ModuleSources = @("main_phone.cpp", "phone.cpp", "viewfinder.cpp", "phone_data.cpp", "services.cpp", "ui.cpp", "arcade.cpp", "duality.cpp", "bumble.cpp", "uranus.cpp", "spacemonkey.cpp", "web.cpp", "config.cpp", "sound.cpp", "picture.cpp", "phone_model.cpp", "phone3d.cpp", "bundle.cpp", "coverage.cpp")
        # The Maps app's map is drawn by the radar's own renderer, carried in
        # the phone - the map only, not the HUD radar (see radar_start.h).
        ExtraSources = @("valkyrie-radar\src\radar_start.cpp", "valkyrie-radar\src\radar3d.cpp", "valkyrie-radar\src\router.cpp")
        ExtraIncludes = @("valkyrie-radar\src")
        CoreSources = @("game.cpp", "radarcfg.cpp", "switches.cpp", "log.cpp", "instrument.cpp", "sprite.cpp", "input.cpp", "script.cpp")
        Defines = @()
    }
)
if ($OnlyTarget -and $OnlyTarget -notin $targets.Name) { throw "Unknown suite target: $OnlyTarget" }

$outputs = @()
foreach ($targetSpec in $targets) {
    if ($OnlyTarget -and $targetSpec.Name -ne $OnlyTarget) { continue }
    $target = $targetSpec
    $name = $target.Name
    $obj = Join-Path $build "obj\$name"
    New-Item -ItemType Directory -Path $obj -Force | Out-Null

    $sources = @($target.ModuleSources | ForEach-Object { "$($target.Module)\src\$_" })
    $sources += @($target.CoreSources | ForEach-Object { "valkyrie-core\src\$_" })
    if ($target.ExtraSources) { $sources += @($target.ExtraSources) }
    $defines = $target.Defines | ForEach-Object { "/D$_" }
    $relativeOut = "build\$name.asi"
    $relativeObj = "build\obj\$name\"
    $relativePdb = "build\$name.pdb"
    $symbolFlags = if ($Release) { "/PDB:$relativePdb" } else { "" }
    $libraries = if ($name -eq "valkyrie-radar") {
        "d3d9.lib user32.lib"
    } elseif ($name -eq "sprp-stats" -or $name -eq "valkyrie-fuel" -or $name -eq "sprp-diagnostics" -or $name -eq "valkyrie-atmosphere") {
        "user32.lib"
    } elseif ($name -eq "valkyrie-phone") {
        # Windows' own image decoder, for web pages, photos and icons; winmm
        # for .wav ringtones; shell32 to put a deleted photo in the Recycle Bin.
        "user32.lib ole32.lib windowscodecs.lib winmm.lib shell32.lib d3d9.lib gdi32.lib d3dcompiler.lib gdiplus.lib"
    } elseif ($name -eq "doctor-valkyrie") {
        "user32.lib gdi32.lib shell32.lib advapi32.lib"
    } else {
        ""
    }
    # doctor-valkyrie's banner is a Win32 resource. Compile it first and pass
    # the resulting .res to the linker, keeping the image inside the ASI.
    $resources = ""
    $trainerObjects = ""
    if ($name -eq "valkyrie-phone") {
        # Everything the phone needs goes inside its ASI (bundle.h): the
        # textures, the ringtones and text tones, and the web page pack when
        # one has been built into build\valkyrie-web.dat. One blob, one
        # resource; the game folder gets only the ASI and its ini.
        $phoneTxd = Join-Path $build "valkyrie-phone.txd"
        & (Join-Path $root "tools\pack-phone-txd.ps1") -Source (Join-Path $root "valkyrie-phone\assets\generated") -Output $phoneTxd -RequiredNames @('app_maps', 'app_camera', 'app_photos', 'app_settings', 'app_phone', 'app_text', 'app_contacts', 'app_internet', 'app_games', 'app_clock', 'app_calculator', 'app_notes', 'app_weather', 'app_stocks', 'app_radio', 'app_calendar', 'app_flashlight')
        $bundleFiles = [Collections.Generic.List[object]]::new()
        $bundleFiles.Add(@("valkyrie-phone.txd", $phoneTxd))
        # The model CJ holds (valkyrie-phone\tools\phone-model) and its textures.
        $modelTxd = Join-Path $build "valkyrie-phone-model.txd"
        & (Join-Path $root "tools\pack-phone-txd.ps1") -Source (Join-Path $root "valkyrie-phone\assets\model\textures") -Output $modelTxd
        $bundleFiles.Add(@("valkyrie-phone-model.dff", (Join-Path $root "valkyrie-phone\assets\model\valkyrie-phone-model.dff")))
        $bundleFiles.Add(@("valkyrie-phone-model.txd", $modelTxd))
        $modelSmTxd = Join-Path $build "valkyrie-phone-model-sm.txd"
        & (Join-Path $root "tools\pack-phone-txd.ps1") -Source (Join-Path $root "valkyrie-phone\assets\model\textures-sm") -Output $modelSmTxd
        $bundleFiles.Add(@("valkyrie-phone-model-sm.txd", $modelSmTxd))
        # The signal the map's masts give, cell by cell (tools\signal-coverage).
        $signal = Join-Path $root "valkyrie-phone\assets\signal\valkyrie-signal.bin"
        if (Test-Path -LiteralPath $signal) { $bundleFiles.Add(@("valkyrie-signal.bin", $signal)) }
        foreach ($kind in "ringtones", "texttones") {
            Get-ChildItem -LiteralPath (Join-Path $root "valkyrie-phone\assets\tones\$kind") -Filter *.wav | Sort-Object Name |
                ForEach-Object { $bundleFiles.Add(@("valkyrie-phone-tones\$kind\$($_.Name)", $_.FullName)) }
        }
        # The browser's pages. The one kept in the repository holds San
        # Andreas' own sites (the real 2004 ones included). GTA IV's
        # internet cannot be kept there - it is built from the player's own
        # copy of GTA IV - so when there is a GTA IV and no pack built from
        # it yet, it is built now, once, into build\: GTA IV's pages laid
        # out by Chrome, San Andreas' taken from the kept pack as they are.
        # Delete build\valkyrie-web.dat to build it again.
        $keptPack = Join-Path $root "valkyrie-phone\assets\web\valkyrie-web.dat"
        $webPack = Join-Path $build "valkyrie-web.dat"
        if (-not (Test-Path -LiteralPath $webPack)) {
            $iv = $Gta4Path
            if ([string]::IsNullOrWhiteSpace($iv)) {
                $candidates = @()
                foreach ($key in "HKLM:\SOFTWARE\WOW6432Node\Rockstar Games\Grand Theft Auto IV", "HKLM:\SOFTWARE\Rockstar Games\Grand Theft Auto IV") {
                    $item = Get-ItemProperty -Path $key -ErrorAction SilentlyContinue
                    if ($item.InstallFolder) { $candidates += $item.InstallFolder }
                }
                foreach ($library in (Get-SteamLibraries)) {
                    foreach ($folder in "Grand Theft Auto IV\GTAIV", "Grand Theft Auto IV", "Grand Theft Auto IV The Complete Edition\GTAIV") {
                        $candidates += (Join-Path $library "steamapps\common\$folder")
                    }
                }
                $iv = $candidates | Where-Object { Test-Path -LiteralPath (Join-Path $_ "pc\html") } | Select-Object -First 1
            }
            $ivHtml = if ($iv) { Join-Path $iv "pc\html" } else { $null }
            if ($ivHtml -and (Test-Path -LiteralPath $ivHtml)) {
                Write-Host "[build] GTA IV: $iv - building the browser's pages from it, once (a few minutes)" -ForegroundColor Cyan
                $python = if (Get-Command py -ErrorAction SilentlyContinue) { @("py", "-3") } else { @("python") }
                $webArgs = @((Join-Path $root "valkyrie-phone\tools\iv-web\build-web-pack.py"), $ivHtml, $webPack, "--with", $keptPack)
                $gxt = Join-Path $iv "pc\text\american.gxt"
                if (Test-Path -LiteralPath $gxt) { $webArgs += @("--gxt", $gxt) }
                $pythonArgs = @($python | Select-Object -Skip 1) + $webArgs
                $built = $false
                try {
                    & $python[0] @pythonArgs
                    $built = $LASTEXITCODE -eq 0
                } catch {
                    Write-Host "[build] $_" -ForegroundColor Yellow
                }
                if (-not $built -or -not (Test-Path -LiteralPath $webPack)) {
                    Remove-Item -LiteralPath $webPack -Force -ErrorAction SilentlyContinue
                    Write-Host "[build] GTA IV's pages could not be built (it needs Python 3, Pillow, Playwright and Chrome - see valkyrie-phone\README.md); San Andreas' sites only this time" -ForegroundColor Yellow
                }
            } else {
                Write-Host "[build] no GTA IV found (give -Gta4Path to use one) - the browser has San Andreas' sites only" -ForegroundColor Yellow
            }
        }
        if (-not (Test-Path -LiteralPath $webPack)) { $webPack = $keptPack }
        Write-Host "[build] browser pages: $webPack" -ForegroundColor Green
        if (Test-Path -LiteralPath $webPack) {
            $bundleFiles.Add(@("valkyrie-web.dat", $webPack))
        } else {
            Write-Host "[build] no build\valkyrie-web.dat - the phone's browser will have no pages (see valkyrie-phone\README.md)" -ForegroundColor Yellow
        }
        $bundlePath = Join-Path $build "obj\$name\valkyrie-phone.bundle"
        New-Item -ItemType Directory -Force -Path (Split-Path $bundlePath) | Out-Null
        $stream = [IO.File]::Create($bundlePath)
        $writer = [IO.BinaryWriter]::new($stream)
        $writer.Write([Text.Encoding]::ASCII.GetBytes("VPAK"))
        $writer.Write([uint32]1)
        $writer.Write([uint32]$bundleFiles.Count)
        foreach ($f in $bundleFiles) {
            $nameBytes = [Text.Encoding]::ASCII.GetBytes($f[0])
            $bytes = [IO.File]::ReadAllBytes($f[1])
            $writer.Write([uint16]$nameBytes.Length)
            $writer.Write($nameBytes)
            $writer.Write([uint32]$bytes.Length)
            $writer.Write($bytes)
        }
        $writer.Dispose()
        Write-Host ("[build] phone bundle: {0} files, {1:N1} MB" -f $bundleFiles.Count, ((Get-Item $bundlePath).Length / 1MB)) -ForegroundColor Green
        $rcPath = Join-Path $build "obj\$name\valkyrie-phone.rc"
        $rcLines = @('1 RCDATA "' + ($bundlePath -replace '\\', '\\') + '"')

        # The trainer is carried in the phone too. It is built on plugin-sdk,
        # Dear ImGui and SafetyHook with settings of its own, so its sources
        # are compiled apart - with exactly what its own build.bat uses, read
        # from there so the two never drift - and linked in with the phone's.
        # Its log and instrument come from the phone's copies of the core.
        $trainerRoot = (Resolve-Path (Join-Path $root "..\valkyrie-trainer")).Path
        $trainerObj = Join-Path $build "obj\$name\trainer"
        New-Item -ItemType Directory -Path $trainerObj -Force | Out-Null
        $bat = Get-Content -LiteralPath (Join-Path $trainerRoot "build.bat")
        $vars = @{ VALKYRIE_CORE = (Join-Path $root "valkyrie-core\src") }
        foreach ($line in $bat) {
            if ($line -match '^set (SDK|SHARED|PLUGINSA|GAMESA|IMGUI)=(.*)$') { $vars[$Matches[1]] = $Matches[2] }
        }
        function Expand-TrainerVars([string]$text) {
            for ($pass = 0; $pass -lt 4; $pass++) {
                foreach ($k in $vars.Keys) { $text = $text.Replace("%$k%", $vars[$k]) }
            }
            return $text
        }
        $trainerInc = Expand-TrainerVars (($bat | Where-Object { $_ -like 'set INC=*' } | Select-Object -First 1).Substring(8))
        $trainerDefs = Expand-TrainerVars (($bat | Where-Object { $_ -like 'set DEFS=*' } | Select-Object -First 1).Substring(9))
        $srcText = ""
        $inSrcs = $false
        foreach ($line in $bat) {
            if ($line -like 'set SRCS=*') { $inSrcs = $true; $line = $line.Substring(9) }
            if (-not $inSrcs) { continue }
            $srcText += " " + $line.TrimEnd('^', ' ')
            if (-not $line.TrimEnd().EndsWith('^')) { break }
        }
        $trainerSources = @([regex]::Matches((Expand-TrainerVars $srcText), '"[^"]+"|\S+') | ForEach-Object { $_.Value.Trim('"') } |
            Where-Object { $_ -and $_ -notmatch '(^|\\)(log|instrument)\.cpp$' })
        $newestSource = (Get-ChildItem -LiteralPath (Join-Path $trainerRoot "src") -File | Measure-Object LastWriteTimeUtc -Maximum).Maximum
        $batTime = (Get-Item -LiteralPath (Join-Path $trainerRoot "build.bat")).LastWriteTimeUtc
        if ($batTime -gt $newestSource) { $newestSource = $batTime }
        $existing = @(Get-ChildItem -LiteralPath $trainerObj -Filter *.obj -ErrorAction SilentlyContinue)
        $oldestObj = ($existing | Measure-Object LastWriteTimeUtc -Minimum).Minimum
        if ($existing.Count -lt $trainerSources.Count -or $oldestObj -lt $newestSource) {
            Get-ChildItem -LiteralPath $trainerObj -Filter *.obj -ErrorAction SilentlyContinue | Remove-Item -Force
            Write-Host "[build] compiling the trainer the phone carries ($($trainerSources.Count) sources)" -ForegroundColor Green
            $quoted = ($trainerSources | ForEach-Object { "`"$_`"" }) -join " "
            $trainerCmd = "`"$vcvars`" x86 >nul && cd /d `"$trainerRoot`" && cl /nologo /c /MP /EHsc /MT /std:c++latest /Zc:__cplusplus $trainerDefs /D VALKYRIE_TRAINER_IN_PHONE $trainerInc $quoted /Fo`"$trainerObj\\`""
            cmd /c $trainerCmd | Select-String -Pattern ' error |fatal' | ForEach-Object { Write-Host $_ -ForegroundColor Red }
            if ($LASTEXITCODE -ne 0) { throw "the trainer the phone carries did not compile" }
        }
        # Listed in a response file: seventy paths overrun cmd's command line.
        $trainerList = Join-Path $build "obj\$name\trainer-objects.rsp"
        Set-Content -LiteralPath $trainerList -Encoding ASCII -Value (Get-ChildItem -LiteralPath $trainerObj -Filter *.obj | ForEach-Object { "`"$($_.FullName)`"" })
        $trainerObjects = "@`"$trainerList`""
        # Its own files, at the resource numbers it reads them by.
        foreach ($line in Get-Content -LiteralPath (Join-Path $trainerRoot "bundle.rc")) {
            if ($line -match '^(\d+)\s+RCDATA\s+"(.+)"$') {
                $file = (Join-Path $trainerRoot $Matches[2]) -replace '/', '\'
                if (-not (Test-Path -LiteralPath $file)) { continue }
                $rcLines += "$($Matches[1]) RCDATA `"$($file -replace '\\', '\\')`""
            }
        }
        Set-Content -LiteralPath $rcPath -Encoding ASCII -Value $rcLines
        $resourceOut = "$relativeObj" + "valkyrie-phone.res"
        $resources = "$resourceOut"
        $resourceCommand = "rc /nologo /fo$resourceOut `"$rcPath`" && "
    } elseif ($name -eq "doctor-valkyrie") {
        $resourceOut = "$relativeObj" + "doctor-valkyrie.res"
        $resources = "$resourceOut"
        $resourceCommand = "rc /nologo /Ivalkyrie-core\src /I$($target.Module)\src /fo$resourceOut $($target.Module)\src\doctor-valkyrie.rc && "
    } else {
        $resourceCommand = ""
    }
    # Presence shares the canonical location/assets tables and JSON dependency.
    $extraIncludes = if ($name -eq "sprp-rpc") { "/I..\sprp-blips\src" } else { "" }
    if ($target.ExtraIncludes) { $extraIncludes += " " + (($target.ExtraIncludes | ForEach-Object { "/I$_" }) -join " ") }
    $cmd = "`"$vcvars`" x86 >nul && cd /d `"$root`" && $resourceCommand" +
           "cl $flags /Ivalkyrie-core\src /I$($target.Module)\src $extraIncludes $($defines -join ' ') $($sources -join ' ') $trainerObjects $resources /Fo$relativeObj /Fe$relativeOut /link /SUBSYSTEM:WINDOWS $linkFlags $symbolFlags $libraries"

    $shownVersion = switch ($name) {
        "valkyrie-atmosphere" { $atmosphereVersion }
        "valkyrie-map"     { $mapVersion }
        "valkyrie-radar"   { $radarVersion }
        "doctor-valkyrie"  { $doctorVersion }
        "valkyrie-phone"   { $phoneVersion }
        default            { $version }
    }
    Write-Host "[build] compiling $name $shownVersion (x86)" -ForegroundColor Green
    cmd /c $cmd
    if ($LASTEXITCODE -ne 0) {
        throw "$name compile failed"
    }

    # An ASI loaded into a 64 bit process does nothing and says nothing about
    # why, so check every output rather than trust the toolchain environment.
    $out = Join-Path $build "$name.asi"
    $bytes = [IO.File]::ReadAllBytes($out)
    $peAt = [BitConverter]::ToInt32($bytes, 0x3C)
    $machine = [BitConverter]::ToUInt16($bytes, $peAt + 4)
    if ($machine -ne 0x14C) {
        throw ("$name has machine 0x{0:X4}, wanted x86 0x014C" -f $machine)
    }

    $outputs += $out
    Write-Host "[build] $out  ($((Get-Item $out).Length) bytes, x86)" -ForegroundColor Green
}

if ($Install) {
    if (-not (Test-Path $game)) {
        throw "No game folder at $game"
    }
    $running = Get-Process gta_sa -ErrorAction SilentlyContinue
    if ($running) {
        throw "Close the game before installing ($(($running.ProcessName | Sort-Object -Unique) -join ', ') is running)"
    }
    foreach ($out in $outputs) {
        Copy-Item $out (Join-Path $game (Split-Path -Leaf $out)) -Force
    }
    Write-Host "[build] installed $($outputs.Count) ASI into $game" -ForegroundColor Green
}
