// Generated by tools/generate-sm-art.py. Do not edit - change the script
// and run it again.
//
// The Shattered Memories handset's keys on sm_body.png, as fractions of
// the texture (x of its width, y of its height, a radius of its width),
// laid out as phone_art.h's body is: its screen is the iFruit's.
#pragma once

namespace phone_art_sm {
// The round pad, where the iFruit's home button is.
constexpr float kPadX = 0.50000f;
constexpr float kPadY = 0.82171f;
constexpr float kPadRadius = 0.10465f;
// A, left of it, and minus, right of it.
constexpr float kAX = 0.20682f;
constexpr float kAY = 0.82752f;
constexpr float kMinusX = 0.79318f;
constexpr float kMinusY = 0.82752f;
constexpr float kKeyRadius = 0.05426f;
}  // namespace phone_art_sm
