// Generated by tools/generate-phone-art.py. Do not edit - change the script
// and run it again.
//
// Where things are on body.png, as fractions of the texture. The texture is
// drawn at width w and height 2w; the body runs from kBodyLeft to kBodyRight, with
// room either side for the side buttons.
#pragma once

namespace phone_art {
constexpr float kBodyAspect = 2.0f;  // height / width
constexpr float kScreenLeft = 0.08140f;
constexpr float kScreenTop = 0.12791f;
constexpr float kScreenRight = 0.91860f;
constexpr float kScreenBottom = 0.75581f;
constexpr float kHomeX = 0.50000f;
constexpr float kHomeY = 0.82171f;
constexpr float kHomeRadius = 0.08140f;  // as a fraction of the width
// The side buttons, left, top, right, bottom: the ring switch and the
// volume buttons on the left edge, the sleep button on the right.
constexpr float kRing[4] = {0.01085f, 0.13566f, 0.03488f, 0.16279f};
constexpr float kVolumeUp[4] = {0.01085f, 0.19380f, 0.03488f, 0.25194f};
constexpr float kVolumeDown[4] = {0.01085f, 0.26744f, 0.03488f, 0.32558f};
constexpr float kSleep[4] = {0.96512f, 0.17829f, 0.98915f, 0.26357f};
constexpr float kBodyBottom = 0.89729f;
constexpr float kBodyLeft = 0.02713f;
constexpr float kBodyRight = 0.97287f;
}  // namespace phone_art
