"""Generate the distributable one-file map builder from reviewed stock sources."""
import base64
import argparse
import io
from pathlib import Path
import zipfile

HERE = Path(__file__).resolve().parent
FILES = ('Build-PhoneMapData.ps1', 'dff-to-gltf.py', 'gen-world-scene.py', 'txd-read.py',
         'world3d-atlas.py', 'world3d-bake.py', 'world3d-index.py',
         'world3d-radar-3dpack.py', 'world3d-radar-texture.py', 'world3d-textures.py')
payload = io.BytesIO()
with zipfile.ZipFile(payload, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
    for name in FILES:
        info = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        archive.writestr(info, (HERE / 'map-data' / name).read_bytes().replace(b'\r\n', b'\n'))
encoded = base64.b64encode(payload.getvalue()).decode('ascii')
script = '''# Generated by make-phone-map-builder.py from tools/map-data.
# Build Maps from your own stock GTA San Andreas files; no radar ASI is installed.
# Install Python 3, then: python -m pip install Pillow numpy
# Sample: .\\build-phone-map.ps1 -GamePath 'C:\\Games\\GTA San Andreas' -Test
# Full:   .\\build-phone-map.ps1 -GamePath 'C:\\Games\\GTA San Andreas'
# Sample builds do not install or share caches with the full map.
param(
    [Parameter(Mandatory)] [string] $GamePath,
    [string] $WorkPath,
    [int] $Jobs = 4,
    [switch] $Test,
    [switch] $SkipInstall
)
$ErrorActionPreference = 'Stop'
if (-not $WorkPath) { $WorkPath = Join-Path $PSScriptRoot 'Valkyrie-phone-map-work' }
$temp = Join-Path ([IO.Path]::GetTempPath()) ('ValkyriePhoneMap-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    $zip = Join-Path $temp 'builder.zip'
    [IO.File]::WriteAllBytes($zip, [Convert]::FromBase64String(@'
__PAYLOAD__
'@))
    Expand-Archive -LiteralPath $zip -DestinationPath $temp
    & (Join-Path $temp 'Build-PhoneMapData.ps1') -GamePath $GamePath -WorkPath $WorkPath -Jobs $Jobs -Test:$Test -SkipInstall:$SkipInstall
} finally {
    $checkedTemp = [IO.Path]::GetFullPath($temp)
    $checkedRoot = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
    if (-not $checkedTemp.StartsWith($checkedRoot, [StringComparison]::OrdinalIgnoreCase)) { throw 'Unexpected temporary path.' }
    if (Test-Path -LiteralPath $checkedTemp) { Remove-Item -LiteralPath $checkedTemp -Recurse -Force }
}
'''.replace('__PAYLOAD__', '\n'.join(encoded[i:i+120] for i in range(0, len(encoded), 120)))
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
output = HERE / 'build-phone-map.ps1'
if args.check:
    if output.read_text(encoding='utf-8') != script:
        raise SystemExit('Phone map builder differs from its reviewed sources; regenerate it.')
    print('Phone map builder matches its reviewed stock sources.')
else:
    output.write_text(script, encoding='utf-8', newline='\r\n')
    print('Generated stock GTA SA phone map builder.')
